### ISSUE TITLE
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by AdityaGovardhan** [oktadeveloper/okta-react-node-example#7]
I was trying to follow the tutorial with **updated** dependencies and here is my code:
https://github.com/AdityaGovardhan/square-hackathon/tree/master/my-react-app

However I am getting this error when I click on POSTS MANAGER button:
```
Executing (default): SELECT count(*) AS `count` FROM `posts` AS `posts`;
Executing (default): SELECT `id`, `title`, `body`, `createdAt`, `updatedAt` FROM `posts` AS `posts` LIMIT 0, 100;
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/express/lib/response.js:771:10)
    at /home/adi/GitHub/square-hackathon/my-react-app/node_modules/epilogue/lib/Controllers/list.js:170:13
    at tryCatcher (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/adi/GitHub/square-hackathon/my-react-app/node_modules/bluebird/js/release/async.js:86:9)
```
This error occurs when I try to add a post too.

Please note that, the code from **this** repo with older dependencies work perfectly. So I am wondering if I introduced this error by using latest dependencies. I am fairly new to React so I couldn't find much relevant help.

**Comment by mraible** [comment]
Replacing epilogue with finale-rest solves this issue for me. I'll update this repo.

https://github.com/dchester/epilogue/issues/239
